#!/usr/bin/env perl
#
#    Copyright (C) 2021 Genome Research Ltd.
#
#    Author: Shane McCarthy <sm15@sanger.ac.uk>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

use strict;
use warnings;
use DateTime;
use Cwd;
use File::Basename;

my $dt = DateTime->now;
my $date = $dt->ymd('');

my $script_dir = dirname Cwd::abs_path(__FILE__);
my $template_dir = qq[$script_dir/../templates];

chdir(qq[$ENV{TOLQCROOT}/sub/bioprojects]);

my %collab_map = (
    'GHC' => 'ASG Sponges-as-Symbiont Hub (https://www.aquaticsymbiosisgenomics.org/collaborators/the-genomic-basis-of-sponge-microbe-symbioses/)',
    'NSU' => 'ASG Photosymbiosis Hub (https://www.aquaticsymbiosisgenomics.org/collaborators/photosymbiosis-across-the-eukaryotic-tree-of-life/)',
    'UDUK' => 'ASG Coral-Symbiosis Hub (https://www.aquaticsymbiosisgenomics.org/collaborators/coral-symbiosis-genome-project/)',
    'DU' => 'ASG Evolution-of-New-Symbioses Hub (https://www.aquaticsymbiosisgenomics.org/collaborators/evolution-of-new-symbioses-in-single-celled-eukaryotes/)',
    'UOBC' => 'ASG Ciliate-Symbiosis Hub (https://www.aquaticsymbiosisgenomics.org/collaborators/ciliates-as-models-for-symbiosis/)',
    'VIEC' => 'ASG Genomic-Signatures Hub (https://www.aquaticsymbiosisgenomics.org/collaborators/genomic-signatures-behind-the-origin-of-multiple-cephalopod-symbiotic-organs/)',
    'QMOUL' => 'ASG Hub (https://www.aquaticsymbiosisgenomics.org/collaborators/bacterial-symbiosis-as-an-adaptation-to-extreme-environments-in-annelid-worms/)',
    'SL' => 'ASG What-Makes-a-Lichen Hub (https://www.aquaticsymbiosisgenomics.org/collaborators/what-makes-a-lichen/)',
    'VIEM' => 'ASG Symbiosis-as-a-Driver-for-Molluscan-Diversity Hub (https://www.aquaticsymbiosisgenomics.org/collaborators/symbiosis-as-a-driver-for-molluscan-diversity/)',
    'URI' => 'ASG Symbiosis-as-a-Driver-for-Molluscan-Diversity Hub (https://www.aquaticsymbiosisgenomics.org/collaborators/symbiosis-as-a-driver-for-molluscan-diversity/)',
    'SENCK' => 'ASG Symbiosis-as-a-Driver-for-Molluscan-Diversity Hub (https://www.aquaticsymbiosisgenomics.org/collaborators/symbiosis-as-a-driver-for-molluscan-diversity/)',
    'PORT' => 'ASG Symbioses-in-3D Hub (https://www.aquaticsymbiosisgenomics.org/collaborators/symbioses-in-3d/)',
    'UOREG' => 'ASG Symbioses-in-3D Hub (https://www.aquaticsymbiosisgenomics.org/collaborators/symbioses-in-3d/)',
    'UCALI' => 'ASG Symbioses-in-3D Hub (https://www.aquaticsymbiosisgenomics.org/collaborators/symbioses-in-3d/)',
);

my %descriptions = (
    # EBP
    'PRJNA533106' => '',
    # DToL
    'PRJEB40665' => 'This project collects the sequencing data and assemblies generated for SPECIES, common name COMMONNAME, by the Darwin Tree of Life Project (https://www.darwintreeoflife.org/). The data under this project are made available subject to the Darwin Tree of Life Open Data Release Policy (https://www.darwintreeoflife.org/project-resources/).',
    # VGP
    'PRJNA489243' => 'This project collects the sequencing data and assemblies generated for SPECIES, common name COMMONNAME. The assembly is provided by the Wellcome Sanger Institute Tree of Life Programme (https://www.sanger.ac.uk/programme/tree-of-life/) in collaboration with COLLABORATOR. The data under this project are made available subject to the Tree of Life Open Data Release Policy (https://www.darwintreeoflife.org/project-resources/).',
    # DToL/VGP
    'PRJEB40665,PRJNA489243' => 'This project collects the sequencing data and assemblies generated for SPECIES, common name COMMONNAME, to facilitate genome assembly and annotation as part of the Darwin Tree of Life Project (https://www.darwintreeoflife.org/). The data under this project are made available subject to the Darwin Tree of Life Open Data Release Policy (https://www.darwintreeoflife.org/project-resources/).',
    # ASG
    'PRJEB43743' => 'This project collects the sequencing data and assemblies generated for SPECIES, common name COMMONNAME, to facilitate genome assembly and annotation as part of the Aquatic Symbiosis Genomics (ASG) Project (https://www.aquaticsymbiosisgenomics.org/) from samples supplied by the COLLABORATOR. The data under this project are made available subject to the Tree of Life Open Data Release Policy (https://www.darwintreeoflife.org/project-resources/).',
    # ToL
    'PRJEB43745' => 'This project collects the sequencing data and assemblies generated for SPECIES, common name COMMONNAME. The assembly is provided by the Wellcome Sanger Institute Tree of Life Programme (https://www.sanger.ac.uk/programme/tree-of-life/) in collaboration with COLLABORATOR. The data under this project are made available subject to the Tree of Life Open Data Release Policy (https://www.darwintreeoflife.org/project-resources/).',
    # 25G
    'PRJEB33226' => 'This project provides the genome assembly of SPECIES, common name COMMONNAME, based on a sample provided by COLLABORATOR.',
    # BAdASS
    'PRJEB51690' => 'This project provides a genome assembly for the mosquito species SPECIES. This assembly was generated by the Anopheles Reference Genomes project. These data (including raw data and assemblies) are released for reuse for any purpose upon deposition in ENA, and we encourage reuse. More information on Sanger’s data release policy can be found here https://www.sanger.ac.uk/about/who-we-are/research-policies/open-access-science/.',
    # ERGA Pilot
    'PRJEB47820' => 'This project collects the sequencing data and assemblies generated for SPECIES, common name COMMONNAME, as part of the European Reference Genome Atlas Pilot Project (https://www.erga-biodiversity.eu/pilot-project). The data under this project are made available subject to the Tree of Life Open Data Release Policy (https://www.darwintreeoflife.org/project-resources/). The assembly is provided by the Wellcome Sanger Institute Tree of Life Programme (https://www.sanger.ac.uk/programme/tree-of-life/) in collaboration with COLLABORATOR.',
    # DToL/ERGA Pilot
    'PRJEB40665,PRJEB47820' => 'This project collects the sequencing data and assemblies generated for SPECIES, common name COMMONNAME, as part of the European Reference Genome Atlas Pilot Project (https://www.erga-biodiversity.eu/pilot-project) and the Darwin Tree of Life Project (https://www.darwintreeoflife.org/). The data under this project are made available subject to the Tree of Life Open Data Release Policy (https://www.darwintreeoflife.org/project-resources/). The assembly is provided by the Wellcome Sanger Institute Tree of Life Programme (https://www.sanger.ac.uk/programme/tree-of-life/) in collaboration with COLLABORATOR.',
);

$descriptions{'PRJEB47820,PRJEB43745,PRJNA489243'} = $descriptions{'PRJEB47820'};
$descriptions{'PRJEB47820,PRJEB43745'} = $descriptions{'PRJEB47820'};
$descriptions{'PRJEB47820,PRJNA489243'} = $descriptions{'PRJEB47820'};
$descriptions{'PRJEB40665,PRJNA489243,PRJEB47820'} = $descriptions{'PRJEB40665,PRJEB47820'};
$descriptions{'PRJEB40665,PRJEB43743'} = $descriptions{'PRJEB40665'};
$descriptions{'PRJEB40665,PRJNA489243,PRJNA1020146'} = $descriptions{'PRJEB40665,PRJNA489243'};

$descriptions{'PRJEB47820,PRJNA1020146,PRJNA489243'} = $descriptions{'PRJEB47820'};
$descriptions{'PRJNA489243,PRJEB47820'} = $descriptions{'PRJEB47820'};
$descriptions{'PRJEB43745,PRJNA489243'} = $descriptions{'PRJEB43745'};

while (<>)
{
    chomp;
    next if /^#/;
    my ($tolid,$asms,$sp,$common,$collab,$taxid,$projects,$data,$umbrella,$cobionts) = split /\t/;
    $data = '' unless ($data);
    $umbrella = '' unless ($umbrella);

    my $spu =$sp;
    $spu =~ s/ /_/g;
    $spu =~ s/'//g;

    my @children = $asms ? split /,/, $asms : ();
    push @children, $data if ($data);
    my @parents = $projects ? split /,/, $projects : ();

    unless (exists $descriptions{$projects} && $descriptions{$projects})
    {
        print STDERR qq[No description setup for projects [$projects]... skipping\n];
        next;
    }
    my $description = $descriptions{$projects};
    if ($cobionts)
    {
        push @children, split(/,/, $cobionts);
        # $description .= ' Add cobiont text?';
    }

    my $template = qq[$template_dir/template.umbrella.xml];
    my $txt = `cat $template`;
    $txt =~ s/PROJECTDESCRIPTION/$description/g;
    if ($umbrella)
    {
        $txt =~ s/IDENTIFIER/accession="$umbrella"/;
    }
    else
    {
        $txt =~ s/IDENTIFIER/alias="ena-tol-$tolid-study-umbrella-$date"/;
    }
    $txt =~ s/SPECIES/$sp/g;
    $txt =~ s/DATE/$date/g;
    $txt =~ s/TOLID/$tolid/g;
    if ($common)
    {
        $txt =~ s/COMMONNAME/$common/g;
    }
    else
    {
        $txt =~ s/, common name COMMONNAME,//g;
        $txt =~ s/, common name COMMONNAME//g;
        $txt =~ s/ \(COMMONNAME\)//g;
    }
    if ($collab)
    {
        my $collab_txt = exists $collab_map{$collab} ? $collab_map{$collab} : $collab;
        $txt =~ s/COLLABORATOR/$collab_txt/g;
    }
    else
    {
        $txt =~ s/ in collaboration with COLLABORATOR//g;
    }
    $txt =~ s/TAXID/$taxid/g;
    my $parents_txt = '';
    foreach my $parent (@parents)
    {
        $parents_txt .= qq[          <RELATED_PROJECT>\n];
        $parents_txt .= qq[            <PARENT_PROJECT accession="$parent" />\n];
        $parents_txt .= qq[          </RELATED_PROJECT>\n];
    }
    $txt =~ s/PARENTS/$parents_txt/;
    my $children_txt = '';
    foreach my $child (@children)
    {
        $children_txt .= qq[          <RELATED_PROJECT>\n];
        $children_txt .= qq[            <CHILD_PROJECT accession="$child" />\n];
        $children_txt .= qq[          </RELATED_PROJECT>\n];
    }
    $txt =~ s/CHILDREN/$children_txt/;
    system(qq[mkdir -p $spu]);
    open(my $fh, ">$spu/$spu.umbrella.$date.xml") || die("Could not write to $spu/$spu.umbrella.$date.xml");
    print $fh $txt;
    close($fh);
    if ($umbrella)
    {
        system(qq[cp $template_dir/template.submission.modify.xml $spu/$spu.umbrella.$date.submission.xml]);
    }
    else
    {
        system(qq[cp $template_dir/template.submission.add.xml $spu/$spu.umbrella.$date.submission.xml]);
    }

    system(qq[tol-register-ena-bioprojects --no_test --prefix $spu/$spu.umbrella.$date]);
}
