#!/usr/bin/env perl
#
#    Copyright (C) 2023 Genome Research Ltd.
#
#    Author: Shane McCarthy <sm15@sanger.ac.uk>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

use strict;
use warnings;
use Data::Dumper;

my %runs;
my $lims = qq[$ENV{TOLQCROOT}/track/tol_pacbio_data.lims.tsv];
$lims = qq[$lims.part] if (-s qq[$lims.part]);
open my $fh, qq[cut -f9,12,13 $lims |];
while (<$fh>)
{
    chomp;
    next if (/^tag/ || /NULL/);
    my (undef, $run, $well) = split /\t/;
    $runs{"$run/$well"} = 1;
}
close($fh);

my %files;
my $irods = qq[$ENV{TOLQCROOT}/track/tol_pacbio_data.fofn];
$irods = qq[$irods.part] if (-s qq[$irods.part]);
open my $fh2, qq[cat $irods |];
while (<$fh2>)
{
    chomp;
    next if (/^file/);
    my @F = split /\t/;
    my $file = $F[0];
    next if ($file =~ /subreads/);
    my $run = $F[5];
    my $well = $F[6];
    $well =~ s/0//;
    next unless (exists $runs{"$run/$well"});
    if ($file =~ m/bc10/ || $file =~ m/bc20/)
    {
        $files{"$run/$well"}{deplex} = $file;
    }
    else
    {
        $files{"$run/$well"}{all} = $file;
    }
}
close($fh2);

my %missing;
while (my ($key, $value) = each %files)
{
    if (exists $$value{all} && !exists $$value{deplex})
    {
        $missing{"$$value{all}"} = 1;
    }
}

open my $fh3, qq[cat $irods |];
while (<$fh3>)
{
    next if (/^file/);
    next if (/Oak Population Genomics/ || /ToL Meiofauna R&D/ || /DTOL_Darwin Tree of Life RNA/ || /ToL Meiofauna RNA R&D/ || /Blaxter_Single nematode genomes/ || /DTOL_Darwin R&D/);
    my @F = split /\t/;
    print $_ if (exists $missing{$F[0]});
}
close($fh3);


exit;
